### ISSUE TITLE
can a layout have a different background color?

### ISSUE THREAD

**Issue by marcelloh** [AllenDang/giu#117]
I've tried to do it with PushColorWindowBg() but that was unsuccessful

**Comment by AllenDang** [comment]
Layout is just a concept not a widget. You could change g.Child's background color using PushColorChildBg

**Comment by AllenDang** [comment]
Layout is just a concept not a widget. You could change g.Child's background color using PushColorChildBg

**Comment by marcelloh** [comment]
PushColorChildBg does not exist (or do I need to update it again?)

**Comment by AllenDang** [comment]
PushColorFrameBg

**Comment by marcelloh** [comment]
Is there an example or documentation where this is used?
I have this, but doesn't work:
```
	g.Layout{
		//g.ListBox("ListBox1", records).OnDClick(func(l int) { fmt.Printf("Clicked %s\n", records[l]) }),
		g.ListBox("ListBox1", records).OnChange(func(l int) { fmt.Printf("Clicked %s\n", records[l]) }),
		g.PushColorFrameBg().RGBA(color.RGBA{
			R: 13,
			G: 13,
			B: 149,
			A: 1,
		}),
	}.Build()
```

**Comment by AllenDang** [comment]
```go
g.Layout{
  g.Custom(func() {g.PushColorFrameBg(...))),
  g.Listbox(..),
  g.Custom(func() {g.PopStyleColor(...)}),
}
```

**Comment by marcelloh** [comment]
Thanks for the hint, but when I do that:
```
g.Layout{
		g.Label("--- layout8 ---"),
		g.Custom(func() {
			g.PushColorFrameBg().RGBA(color.RGBA{
				R: 13,
				G: 13,
				B: 149,
				A: 1,
			})
		}),
		buttons,
	}.Build()
```
it tells me it's wrong: g.PushColorFrameBg() (no value) used as value or type

I don't know how the g.PopStyleColor(...)} works :-(

So I changed it into:
```
g.PushColorFrameBg(color.RGBA{
				R: 13,
				G: 13,
				B: 149,
				A: 1,
			})
```
which compiles but gives me a run time exception (and my program, stops)
```
Assertion failed: (*p >= n && "PushStyleColor/PopStyleColor Mismatch!"), function ErrorCheckBeginEndCompareStacksSize, file imgui.cpp, line 6953.
SIGABRT: abort
PC=0x7fff20331462 m=0 sigcode=0
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x42053c0, 0xc00005dd48, 0x1)
        /usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc00005dd18 sp=0xc00005dce0 pc=0x400889b
github.com/AllenDang/giu/imgui._Cfunc_iggEnd()
        _cgo_gotypes.go:1808 +0x45 fp=0xc00005dd48 sp=0xc00005dd18 pc=0x4110d85
github.com/AllenDang/giu/imgui.End(...)
        /Users/marcelloh/data/go-speeltuin/Giu/vendor/github.com/AllenDang/giu/imgui/imgui.go:88
github.com/AllenDang/giu.(*WindowWidget).Layout(0xc0000ab740, 0xc00005ddb0, 0x2, 0x2)
        /Users/marcelloh/data/go-speeltuin/Giu/vendor/github.com/AllenDang/giu/Window.go:82 +0xf8 fp=0xc00005dd80 sp=0xc00005dd48 pc=0x41f8ed8
main.loop()
        /Users/marcelloh/data/go-speeltuin/Giu/main.go:335 +0xb9 fp=0xc00005dde0 sp=0xc00005dd80 pc=0x42018b9
github.com/AllenDang/giu.(*MasterWindow).render(0xc000161420)
        /Users/marcelloh/data/go-speeltuin/Giu/vendor/github.com/AllenDang/giu/MasterWindow.go:172 +0xc5 fp=0xc00005de60 sp=0xc00005dde0 pc=0x41f6105
github.com/AllenDang/giu.(*MasterWindow).run.func1()
        /Users/marcelloh/data/go-speeltuin/Giu/vendor/github.com/AllenDang/giu/MasterWindow.go:190 +0x59 fp=0xc00005dea0 sp=0xc00005de60 pc=0x41f90f9
github.com/AllenDang/giu.Call.func1()
        /Users/marcelloh/data/go-speeltuin/Giu/vendor/github.com/AllenDang/giu/MainThread.go:67 +0x2f fp=0xc00005ded0 sp=0xc00005dea0 pc=0x41f8fef
github.com/AllenDang/giu.Run(0xc00000ea20)
        /Users/marcelloh/data/go-speeltuin/Giu/vendor/github.com/AllenDang/giu/MainThread.go:53 +0x72 fp=0xc00005df08 sp=0xc00005ded0 pc=0x41f4af2
github.com/AllenDang/giu.(*MasterWindow).Run(0xc000161420, 0x434e0d8)
        /Users/marcelloh/data/go-speeltuin/Giu/vendor/github.com/AllenDang/giu/MasterWindow.go:237 +0x65 fp=0xc00005df28 sp=0xc00005df08 pc=0x41f6425
main.main()
        /Users/marcelloh/data/go-speeltuin/Giu/main.go:347 +0x19f fp=0xc00005df88 sp=0xc00005df28 pc=0x4201a7f
runtime.main()
        /usr/local/go/src/runtime/proc.go:204 +0x209 fp=0xc00005dfe0 sp=0xc00005df88 pc=0x403c5c9
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc00005dfe8 sp=0xc00005dfe0 pc=0x406d761

goroutine 6 [chan receive]:
github.com/AllenDang/giu.Call(0xc0000ab710)
        /Users/marcelloh/data/go-speeltuin/Giu/vendor/github.com/AllenDang/giu/MainThread.go:68 +0xaa
github.com/AllenDang/giu.(*MasterWindow).run(0xc000161420)
        /Users/marcelloh/data/go-speeltuin/Giu/vendor/github.com/AllenDang/giu/MasterWindow.go:188 +0xa5
github.com/AllenDang/giu.(*MasterWindow).Run.func1()
        /Users/marcelloh/data/go-speeltuin/Giu/vendor/github.com/AllenDang/giu/MasterWindow.go:242 +0x4d
github.com/AllenDang/giu.Run.func1(0xc00000ea20, 0xc0001000c0)
        /Users/marcelloh/data/go-speeltuin/Giu/vendor/github.com/AllenDang/giu/MainThread.go:50 +0x27
created by github.com/AllenDang/giu.Run
        /Users/marcelloh/data/go-speeltuin/Giu/vendor/github.com/AllenDang/giu/MainThread.go:50 +0x6b

rax    0x0
rbx    0x14149e00
rcx    0x7ffeefbff418
rdx    0x0
rdi    0x307
rsi    0x6
rbp    0x7ffeefbff440
rsp    0x7ffeefbff418
r8     0x1b29
r9     0xcccccccccccccccd
r10    0x14149e00
r11    0x246
r12    0x307
r13    0x43de2000
r14    0x6
r15    0x16
rip    0x7fff20331462
rflags 0x246
cs     0x7
fs     0x0
gs     0x0
exit status 2:
```

**Comment by AllenDang** [comment]
@marcelloh My previous code demo tells you, and I quote it again as below shows.

```go
g.Layout{
  g.Custom(func() {g.PushColorFrameBg(...))),
  // The frame backgorund color will be changed from here.
  g.Listbox(..),
  // The frame background color will be reset to default.
  g.Custom(func() {g.PopStyleColor(...)}),
}
```
Invoke PushColorFrameBg will change the FrameBg untill PopStyleColor is invoked. And they should always be invoked in pair. 

BTW, whats editor you are using? I noticed you are typing code without any auto-completion and function parameter hint.

**Comment by marcelloh** [comment]
using VSC with auto-completion.
but since I really don't know how I should look at this g.PopStyleColor(...) I don't know.
Push and Pop is known for usage on a stack. So I should know that Push add a color to the stack which will be the color in use. 
Pop should remove one of the stack (so it is unclear why it has params for me)

But I've tried and came up with this, which complies but doesn't do anything with a color:
```
	g.Layout{
		g.Label("--- layout8 ---"),
		g.Custom(func() {
			g.PushColorFrameBg(color.RGBA{
				R: 13,
				G: 13,
				B: 255,
				A: 1,
			})
		}),
		g.Label("--- be4 buttons ---"),
		g.Custom(func() { g.PopStyleColor() }),
		g.Label("--- after buttons ---"),
		buttons,
	}.Build()

```

**Comment by AllenDang** [comment]
@marcelloh You need to know how the style system of imgui works. There are lots of colors could be set for different widgets.
In you code, you changed the frame background, but label doesn't have a background, only thing label has is just text, so you cannot change background color for it.
To change a Child's background color, use code like below.

```go
package main

import (
	"image/color"

	g "github.com/AllenDang/giu"
	"github.com/AllenDang/giu/imgui"
)

func loop() {
	g.SingleWindow("hello world").Layout(g.Layout{
		g.Label("Hello world from giu"),
		g.Custom(func() {
			imgui.PushStyleColor(imgui.StyleColorChildBg, g.ToVec4Color(color.RGBA{R: 13, G: 13, B: 13, A: 255}))
		}),
		g.Child("Different Bg").Size(200, 100).Layout(g.Layout{}),
		g.Custom(func() { g.PopStyleColor() }),
	})
}

func main() {
	wnd := g.NewMasterWindow("Hello world", 400, 200, g.MasterWindowFlagsNotResizable, nil)
	wnd.Run(loop)
}
```

**Comment by marcelloh** [comment]
Ok, now this was really helpful, thank you.
