### ISSUE TITLE
g.OpenPopup() in function?

### ISSUE THREAD

**Issue by HACKERALERT** [AllenDang/giu#191]
```go
g.Button("Popup Modal").OnClick(btnPopupCLicked),
g.PopupModal("Confirm").Layout(
        g.Label("Confirm to close me?"),
        g.Row(
                g.Button("Yes").OnClick(func() { g.CloseCurrentPopup() }),					 
                g.Button("No"),
        ),
),
```
^ Works as expected. When I click the button, the modal shows. But, when I call it from a function like this:

```go
if logic{
    g.OpenPopup("Confirm")
}
```
I get a segmentation fault:
```bash
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc8 pc=0x6d5ea2]

runtime stack:
runtime.throw(0x951cbc, 0x2a)
	/usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:718 +0x2e5

goroutine 290 [syscall]:
runtime.cgocall(0x6a67f0, 0xc000433508, 0x7fd44c000d40)
	/usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc0004334d8 sp=0xc0004334a0 pc=0x48775b
github.com/AllenDang/imgui-go._Cfunc_iggOpenPopup(0x7fd44c000d40)
	_cgo_gotypes.go:4588 +0x3c fp=0xc000433508 sp=0xc0004334d8 pc=0x5d289c
github.com/AllenDang/imgui-go.OpenPopup(0x940ae6, 0x7)
	/home/evansu/go/pkg/mod/github.com/!allen!dang/imgui-go@v1.12.1-0.20210509113325-c0e4c78e7a88/imgui.go:1084 +0x67 fp=0xc000433548 sp=0xc000433508 pc=0x5d6f07
github.com/AllenDang/giu.OpenPopup(...)
	/home/evansu/go/pkg/mod/github.com/!allen!dang/giu@v0.5.4/Widgets.go:1246
main.confirmOverwrite(...)
	/home/evansu/Documents/Picocrypt/Picocrypt.go:1130
main.work()
	/home/evansu/Documents/Picocrypt/Picocrypt.go:604 +0x32f8 fp=0xc000433fe0 sp=0xc000433548 pc=0x6a12f8
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000433fe8 sp=0xc000433fe0 pc=0x4ee721
created by main.startUI.func6
	/home/evansu/Documents/Picocrypt/Picocrypt.go:245 +0x35

goroutine 1 [runnable, locked to thread]:
github.com/AllenDang/imgui-go.(*Vec2).wrapped(0xc0003d2660, 0xc0003d2660, 0xc0001c03e0)
	/home/evansu/go/pkg/mod/github.com/!allen!dang/imgui-go@v1.12.1-0.20210509113325-c0e4c78e7a88/Vectors.go:14 +0x78
github.com/AllenDang/imgui-go.DrawData.ScaleClipRects(0x194a660, 0x3f8000003f800000)
	/home/evansu/go/pkg/mod/github.com/!allen!dang/imgui-go@v1.12.1-0.20210509113325-c0e4c78e7a88/DrawData.go:40 +0x50
github.com/AllenDang/imgui-go.(*OpenGL3).Render(0xc00006c3c0, 0x43f8000043f00000, 0x43f8000043f00000, 0x194a660)
	/home/evansu/go/pkg/mod/github.com/!allen!dang/imgui-go@v1.12.1-0.20210509113325-c0e4c78e7a88/RendererOpenGL3.go:83 +0xac
github.com/AllenDang/giu.(*MasterWindow).render(0xc00015b420)
	/home/evansu/go/pkg/mod/github.com/!allen!dang/giu@v0.5.4/MasterWindow.go:178 +0x11c
github.com/AllenDang/giu.(*MasterWindow).run.func1()
	/home/evansu/go/pkg/mod/github.com/!allen!dang/giu@v0.5.4/MasterWindow.go:193 +0x59
github.com/faiface/mainthread.Call.func1()
	/home/evansu/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:63 +0x2f
github.com/faiface/mainthread.Run(0xc00000e5d0)
	/home/evansu/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:44 +0xb1
github.com/AllenDang/giu.(*MasterWindow).Run(0xc00015b420, 0x95ac48)
	/home/evansu/go/pkg/mod/github.com/!allen!dang/giu@v0.5.4/MasterWindow.go:250 +0x65
main.main()
	/home/evansu/Documents/Picocrypt/Picocrypt.go:1171 +0xc5

goroutine 6 [chan receive]:
github.com/faiface/mainthread.Call(0xc0001b5b60)
	/home/evansu/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:66 +0xc5
github.com/AllenDang/giu.(*MasterWindow).run(0xc00015b420)
	/home/evansu/go/pkg/mod/github.com/!allen!dang/giu@v0.5.4/MasterWindow.go:191 +0xa5
github.com/AllenDang/giu.(*MasterWindow).Run.func1()
	/home/evansu/go/pkg/mod/github.com/!allen!dang/giu@v0.5.4/MasterWindow.go:255 +0x4d
github.com/faiface/mainthread.Run.func1(0xc00000e5d0, 0xc0000261e0)
	/home/evansu/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:37 +0x27
created by github.com/faiface/mainthread.Run
	/home/evansu/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:36 +0xa5
exit status 2
```

Any ideas on how I can dynamically open a modal, instead of having to bind it to a widget? Thank you.

**Comment by AllenDang** [comment]
Are you invoking `g.OpenPopup` from different goroutine?

**Comment by AllenDang** [comment]
Here is a working demo.

```go
package main

import (
	g "github.com/AllenDang/giu"
)

var (
	content string
)

func onOpenPopup() {
	g.OpenPopup("Open me")
}

func loop() {
	g.SingleWindow("hello world").Layout(
		g.Button("Open popup").OnClick(onOpenPopup),
		g.InputTextMultiline("##content", &content).Size(-1, -1),
		g.PopupModal("Open me").Layout(
			g.Label("Close me now"),
			g.Button("Close").OnClick(func() { g.CloseCurrentPopup() }),
		),
	)
}

func main() {
	wnd := g.NewMasterWindow("Hello world", 400, 200, 0)
	wnd.Run(loop)
}
```

**Comment by HACKERALERT** [comment]
I was indeed running it from a goroutine. I'm running from the main thead now and everything works. Thank you!
