### ISSUE TITLE
macOS OpenGL issue

### ISSUE THREAD

**Issue by HACKERALERT** [AllenDang/giu#202]
```
Unable to create basic Accelerated OpenGL renderer.
Unable to create basic Accelerated OpenGL renderer.
Core Image is now using the software OpenGL renderer. This will be slow.
GLFW: An invalid error was not accepted by the caller: FormatUnavailable: NSGL: Failed to find a suitable pixel format
GLFW: Please report this bug in the Go package immediately.
panic: FormatUnavailable: NSGL: Failed to find a suitable pixel format

goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.acceptError(0xc00008dde8, 0x2, 0x2, 0x0, 0x0)
	/Users/XXXXXX/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20210410170116-ea3d685f79fb/error.go:178 +0x20c
github.com/go-gl/glfw/v3.3/glfw.CreateWindow(0x1e0, 0x1e8, 0x4654c9a, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/XXXXXX/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20210410170116-ea3d685f79fb/window.go:350 +0x197
github.com/AllenDang/imgui-go.NewGLFW(0x600b808, 0x4654c9a, 0x9, 0x1e0, 0x1e8, 0xc000020001, 0x40431ae, 0xc00008def8, 0x4066860)
	/Users/XXXXXX/go/pkg/mod/github.com/!allen!dang/imgui-go@v1.12.1-0.20210509113325-c0e4c78e7a88/PlatformGlfw.go:90 +0x1e9
github.com/AllenDang/giu.NewMasterWindow(0x4654c9a, 0x9, 0x1e0, 0x1e8, 0x1, 0x0, 0x48a88a8)
	/Users/XXXXXX/go/pkg/mod/github.com/!allen!dang/giu@v0.5.4/MasterWindow.go:51 +0xfb
main.main()
	/Users/XXXXXX/Downloads/Picocrypt-main/src/Picocrypt.go:1643 +0x72

[Process completed]
```

I'm running macOS Catalina in a VirtualBox with KVM acceleration, host is Debian 11 with GNOME.

I have already `brew install glfw3` and `brew install glew`. Any ideas? I don't use macOS and I'm only doing so now to build my software so I can publish it. Maybe update to Big Sur? Thank you.

**Comment by AllenDang** [comment]
Seems VirtualBox doesn't support OpenGL.
