### ISSUE TITLE
Crash in InputText with InputTextFlagsPassword set

### ISSUE THREAD

**Issue by dFionov** [AllenDang/giu#211]
Repro:
```Go
package main

import g "github.com/AllenDang/giu"

var (
	pass string
)
func loop() {
	g.SingleWindow("title").Layout(
		g.InputText("Password", &pass).Flags(g.InputTextFlagsPassword),
	)
}
func main() {
	wnd := g.NewMasterWindow("Hello world", 700, 700, 0)
	wnd.Run(loop)
}
```
Exception:
```
Exception 0xc00000fd 0x1 0x2da3ff0 0x180003e2a
PC=0x180003e2a
signal arrived during external code execution

github.com/AllenDang/imgui-go._Cfunc_iggInputTextWithHint(0x2a72b530, 0x2a6a7bb0, 0x2a6a7b70, 0x4800000000002, 0x1, 0x0)
        _cgo_gotypes.go:4004 +0x54
github.com/AllenDang/imgui-go.InputTextWithHint(0xa0d7db, 0x8, 0x0, 0x0, 0xca0a70, 0x8000, 0x0, 0xc000032000)
        C:/src/go/pkg/mod/github.com/!allen!dang/imgui-go@v1.12.1-0.20210608122117-caa79ce954d4/imgui.go:608 +0x15b
github.com/AllenDang/giu.(*InputTextWidget).Build(0xc0000d0c00)
        C:/src/go/pkg/mod/github.com/!allen!dang/giu@v0.5.5-0.20210608122408-7b2ce215ffe3/Widgets.go:990 +0x104
github.com/AllenDang/giu.Layout.Build(0xc0000c9d88, 0x1, 0x1)
        C:/src/go/pkg/mod/github.com/!allen!dang/giu@v0.5.5-0.20210608122408-7b2ce215ffe3/Layout.go:12 +0x6d
github.com/AllenDang/giu.(*WindowWidget).Layout(0xc0000b77d0, 0xc0000c9d88, 0x1, 0x1)
        C:/src/go/pkg/mod/github.com/!allen!dang/giu@v0.5.5-0.20210608122408-7b2ce215ffe3/Window.go:81 +0x12a
main.loop()
        C:/src/go/src/bitbucket.org/dFionov/gofen/frontend/giu/main.go:31 +0x125
github.com/AllenDang/giu.(*MasterWindow).render(0xc0001c6150)
        C:/src/go/pkg/mod/github.com/!allen!dang/giu@v0.5.5-0.20210608122408-7b2ce215ffe3/MasterWindow.go:183 +0xb0
github.com/AllenDang/giu.(*MasterWindow).run.func1()
        C:/src/go/pkg/mod/github.com/!allen!dang/giu@v0.5.5-0.20210608122408-7b2ce215ffe3/MasterWindow.go:201 +0x60
github.com/faiface/mainthread.Call.func1()
        C:/src/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:63 +0x36
github.com/faiface/mainthread.Run(0xc000096f60)
        C:/src/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:44 +0xc4
github.com/AllenDang/giu.(*MasterWindow).Run(0xc0001c6150, 0xa2c878)
        C:/src/go/pkg/mod/github.com/!allen!dang/giu@v0.5.5-0.20210608122408-7b2ce215ffe3/MasterWindow.go:258 +0x67
main.main()
        main.go:37 +0x6e

goroutine 19 [chan receive]:
github.com/faiface/mainthread.Call(0xc0000b77a0)
        C:/src/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:66 +0xc9
github.com/AllenDang/giu.(*MasterWindow).run(0xc0001c6150)
        C:/src/go/pkg/mod/github.com/!allen!dang/giu@v0.5.5-0.20210608122408-7b2ce215ffe3/MasterWindow.go:199 +0xa9
github.com/AllenDang/giu.(*MasterWindow).Run.func1()
        C:/src/go/pkg/mod/github.com/!allen!dang/giu@v0.5.5-0.20210608122408-7b2ce215ffe3/MasterWindow.go:263 +0x54
github.com/faiface/mainthread.Run.func1(0xc000096f60, 0xc000086540)
        C:/src/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:37 +0x2e
created by github.com/faiface/mainthread.Run
        C:/src/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:36 +0xb8
rax     0x180003ff0
rbx     0x2da4970
rcx     0x2da4018
rdi     0x72ba52
rsi     0x0
rbp     0x1
rsp     0x2da3ff8
r8      0x0
r9      0x1772
r10     0x3001f10
r11     0x1
r12     0x32ba52
r13     0x400000
r14     0xc91c00
r15     0x0
rip     0x180003e2a
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b

```

**Comment by AllenDang** [comment]
@dFionov Thanks to report this issue. I can repo at my side. Checking it now.

**Comment by AllenDang** [comment]
@dFionov It is fixed.
