### ISSUE TITLE
fatal panic on starting giu

### ISSUE THREAD

**Issue by gucio321** [AllenDang/giu#212]
Yo,
I just noticed, that `giu` doesn't start on my machine anymore.
When I'm running any example/code, it crashes with a following panic:
```console
widgets: imgui.cpp:7192: void ImGui::ErrorCheckNewFrameSanityChecks(): Assertion `g.IO.Fonts->Fonts[0]->IsLoaded() && "Font Atlas not built. Did you call io.Fonts->GetTexDataAsRGBA32() / GetTexDataAsAlpha8()?"' failed.
SIGABRT: abort
PC=0x7f31fc71b9e5 m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x634e60, 0xc00011fda0, 0x4000)
	/usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc00011fd70 sp=0xc00011fd38 pc=0x48673b
github.com/AllenDang/imgui-go._Cfunc_iggNewFrame()
	_cgo_gotypes.go:4742 +0x3c fp=0xc00011fda0 sp=0xc00011fd70 pc=0x57d1dc
github.com/AllenDang/imgui-go.NewFrame(...)
	/home/username/go/pkg/mod/github.com/!allen!dang/imgui-go@v1.12.1-0.20210610115201-3253c355762e/imgui.go:30
github.com/AllenDang/giu.(*MasterWindow).render(0xc00031a000)
	/run/media/username/SALATKA/mystuff/test/giu/MasterWindow.go:182 +0x9b fp=0xc00011fe10 sp=0xc00011fda0 pc=0x62505b
github.com/AllenDang/giu.(*MasterWindow).run.func1()
	/run/media/username/SALATKA/mystuff/test/giu/MasterWindow.go:201 +0x59 fp=0xc00011fe50 sp=0xc00011fe10 pc=0x629eb9
github.com/faiface/mainthread.Call.func1()
	/home/username/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:63 +0x2f fp=0xc00011fe80 sp=0xc00011fe50 pc=0x58b48f
github.com/faiface/mainthread.Run(0xc0003184e0)
	/home/username/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:44 +0xb1 fp=0xc00011ff08 sp=0xc00011fe80 pc=0x58b211
github.com/AllenDang/giu.(*MasterWindow).Run(0xc00031a000, 0x8dcd58)
	/run/media/username/SALATKA/mystuff/test/giu/MasterWindow.go:258 +0x65 fp=0xc00011ff28 sp=0xc00011ff08 pc=0x625305
main.main()
	/run/media/username/SALATKA/mystuff/test/giu/examples/widgets/widgets.go:211 +0x18f fp=0xc00011ff88 sp=0xc00011ff28 pc=0x63196f
runtime.main()
	/usr/local/go/src/runtime/proc.go:225 +0x256 fp=0xc00011ffe0 sp=0xc00011ff88 pc=0x4bb4f6
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc00011ffe8 sp=0xc00011ffe0 pc=0x4ed101

goroutine 18 [chan receive]:
github.com/faiface/mainthread.Call(0xc000240ba0)
	/home/username/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:66 +0xc5
github.com/AllenDang/giu.(*MasterWindow).run(0xc00031a000)
	/run/media/username/SALATKA/mystuff/test/giu/MasterWindow.go:199 +0xa5
github.com/AllenDang/giu.(*MasterWindow).Run.func1()
	/run/media/username/SALATKA/mystuff/test/giu/MasterWindow.go:263 +0x4d
github.com/faiface/mainthread.Run.func1(0xc0003184e0, 0xc000320000)
	/home/username/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:37 +0x27
created by github.com/faiface/mainthread.Run
	/home/username/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:36 +0xa5

rax    0x0
rbx    0x7f31fc593740
rcx    0x7f31fc71b9e5
rdx    0x0
rdi    0x2
rsi    0x7ffd630b7c70
rbp    0x7f31fc871680
rsp    0x7ffd630b7c70
r8     0x0
r9     0x7ffd630b7c70
r10    0x8
r11    0x246
r12    0x91a372
r13    0x1c18
r14    0x91e618
r15    0xffffffffffffffff
rip    0x7f31fc71b9e5
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
exit status 2
```

I'm running examples/widgets.

my system:
- OS: Fedora 33
- desktop: gnome-shell 3.38.4

**Comment by gucio321** [comment]
I think, it stopped working when ddbd02d072fc6942fa264259a7bfd1d5f6d98b7e was commited

**Comment by gucio321** [comment]
also might be related with this panic: https://github.com/AllenDang/giu/issues/171

**Comment by AllenDang** [comment]
@gucio321 Can you post the demo code?

**Comment by gucio321** [comment]
@AllenDang  generally any code deosn't work for me
<details><summary>e.g. this hello world example</summary>

```golang
package main

import (
	g "github.com/AllenDang/giu"
)

var (
	content string
)

func loop() {
	g.SingleWindow("hello world").Layout(
		g.Label("Hello world from giu"),
		g.InputTextMultiline("##content", &content).Size(-1, -1),
	)
}

func main() {
	wnd := g.NewMasterWindow("Hello world", 400, 200, 0)
	wnd.Run(loop)
}
```

</details>

<details><summary>panic message is here</summary>

```console
helloworld: imgui.cpp:7192: void ImGui::ErrorCheckNewFrameSanityChecks(): Assertion `g.IO.Fonts->Fonts[0]->IsLoaded() && "Font Atlas not built. Did you call io.Fonts->GetTexDataAsRGBA32() / GetTexDataAsAlpha8()?"' failed.
SIGABRT: abort
PC=0x7f09c14727d5 m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x61d010, 0xc0000b5dc0, 0x4000)
	/usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc0000b5d90 sp=0xc0000b5d58 pc=0x48673b
github.com/AllenDang/imgui-go._Cfunc_iggNewFrame()
	_cgo_gotypes.go:4742 +0x3c fp=0xc0000b5dc0 sp=0xc0000b5d90 pc=0x5760dc
github.com/AllenDang/imgui-go.NewFrame(...)
	/home/username/go/pkg/mod/github.com/!allen!dang/imgui-go@v1.12.1-0.20210610115201-3253c355762e/imgui.go:30
github.com/AllenDang/giu.(*MasterWindow).render(0xc000288000)
	/home/username/giu/MasterWindow.go:182 +0x9b fp=0xc0000b5e30 sp=0xc0000b5dc0 pc=0x61937b
github.com/AllenDang/giu.(*MasterWindow).run.func1()
	/home/username/giu/MasterWindow.go:201 +0x59 fp=0xc0000b5e70 sp=0xc0000b5e30 pc=0x619cb9
github.com/faiface/mainthread.Call.func1()
	/home/username/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:63 +0x2f fp=0xc0000b5ea0 sp=0xc0000b5e70 pc=0x580c4f
github.com/faiface/mainthread.Run(0xc00000e4f8)
	/home/username/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:44 +0xb1 fp=0xc0000b5f28 sp=0xc0000b5ea0 pc=0x5809d1
github.com/AllenDang/giu.(*MasterWindow).Run(0xc000288000, 0x8bed80)
	/home/username/giu/MasterWindow.go:258 +0x65 fp=0xc0000b5f48 sp=0xc0000b5f28 pc=0x619625
main.main()
	/home/username/giu/examples/helloworld/helloworld.go:20 +0x67 fp=0xc0000b5f88 sp=0xc0000b5f48 pc=0x61a5e7
runtime.main()
	/usr/local/go/src/runtime/proc.go:225 +0x256 fp=0xc0000b5fe0 sp=0xc0000b5f88 pc=0x4bb4f6
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0000b5fe8 sp=0xc0000b5fe0 pc=0x4ed101

goroutine 5 [chan receive]:
github.com/faiface/mainthread.Call(0xc00007c030)
	/home/username/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:66 +0xc5
github.com/AllenDang/giu.(*MasterWindow).run(0xc000288000)
	/home/username/giu/MasterWindow.go:199 +0xa5
github.com/AllenDang/giu.(*MasterWindow).Run.func1()
	/home/username/giu/MasterWindow.go:263 +0x4d
github.com/faiface/mainthread.Run.func1(0xc00000e4f8, 0xc000026060)
	/home/username/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:37 +0x27
created by github.com/faiface/mainthread.Run
	/home/username/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:36 +0xa5

rax    0x0
rbx    0x7f09c12e5740
rcx    0x7f09c14727d5
rdx    0x0
rdi    0x2
rsi    0x7ffee52cd140
rbp    0x7f09c15c90d8
rsp    0x7ffee52cd140
r8     0x0
r9     0x7ffee52cd140
r10    0x8
r11    0x246
r12    0x8f7b72
r13    0x1c18
r14    0x8fbe18
r15    0xffffffffffffffff
rip    0x7f09c14727d5
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
exit status 2
```

</details>

**Comment by gucio321** [comment]
@allenDang If I comment out default font for my system (like in 27a6345 ) gpp starts

**Comment by AllenDang** [comment]
@gucio321 How about now? Does it still crash?

**Comment by gucio321** [comment]
yah,, the same panic

**Comment by AllenDang** [comment]
@gucio321 Can you add `fmt.Println(fontInfo)` to `FontAtlasProsesor.go` at line 201 and post the printed content ?

**Comment by gucio321** [comment]
```console
{Cantarell /usr/share/fonts/cantarell/Cantarell-VF.otf [] 15}
```

**Comment by AllenDang** [comment]
@gucio321 What's the return value of `fonts.AddFontFromFileTTFV(fontInfo.fontPath, fontInfo.size, fontConfig, ranges.Data())`

**Comment by gucio321** [comment]
@AllenDang still crashes

> @gucio321 What's the return value of fonts.AddFontFromFileTTFV(fontInfo.fontPath, fontInfo.size, fontConfig, ranges.Data())

`49777936`

**Comment by AllenDang** [comment]
@gucio321 It's really weired...

**Comment by gucio321** [comment]
> @gucio321 It's really weired...

Thats only thing I'm sure of :smile:

**Comment by AllenDang** [comment]
@gucio321 Ok... I removed cantarell. Still curious about why...

**Comment by gucio321** [comment]
> https://github.com/AllenDang/giu/issues/171#issuecomment-825474452

maybe `imgui` can't read this font?
well, it can read but cannot find any glyphs in it?...
just my guess, I didn't check it any way

**Comment by gucio321** [comment]
yah, thats deffinitly font's fault - any other font works.
so `cantarel` cannot be used.
<details><summary>here is a content of my `/usr/share/fonts` directory</summary>

```console
aajohan-comfortaa
abattis-cantarell
adobe-source-code-pro
adobe-source-han-sans-cn
adobe-source-han-sans-tw
adobe-source-han-serif-cn
adobe-source-han-serif-tw
blender
cantarell
dejavu-sans-fonts
dejavu-sans-mono-fonts
dejavu-serif-fonts
gdouros-symbola
gnu-free
google-carlito-fonts
google-droid-sans-fonts
google-noto
google-noto-cjk
google-noto-emoji
google-noto-vf
ht-caladea-fonts
jomolhari-fonts
julietaula-montserrat
khmeros
lato
liberation-mono
liberation-narrow
liberation-sans
liberation-serif
lm
lm-math
lohit-assamese
lohit-bengali
lohit-devanagari
lohit-gujarati
lohit-gurmukhi
lohit-kannada
lohit-odia
lohit-tamil
lohit-telugu
lyx
material-icons-fonts
mnsymbol
naver-nanum
open-sans
opensymbol
paktype-naskh-basic
pt-sans-fonts
sil-abyssinica-fonts
sil-mingzat
sil-nuosu
sil-padauk
smc
smc-anjalioldlipi
smc-dyuthi
smc-meera
smc-rachana
smc-raghumalayalamsans
smc-suruma
stix-fonts
tabish-eeyek
tex-gyre
tex-gyre-math
TeXmacs
thai-scalable
urw-base35
vlgothic
wine-tahoma-fonts
wine-times-new-roman-fonts
wine-wingdings-fonts
```

</details>

Lot of users might have `wine` installed, so I suggest you to add `wine-times-new-roman-fonts`
you can also add some other popular fonts e.g. `gnu-free` but it doesn't look so beautiful
also let's add some of google fonts from here e.g. `google-noto` - it looks very cool
so order of default fonts I suggest:
- `google-noto`
- `wine-times-new-roman-fonts`
- `gnu-free`

**Comment by gucio321** [comment]
the only question left is: why `cantarell` doesn't work :smile:

**Comment by AllenDang** [comment]
@gucio321 Can you rise a PR to add google-note? I think it looks cool.

**Comment by gucio321** [comment]
@AllenDang thats really strange, but atm I'm on other my machine and google-noto looks like:
![image](https://user-images.githubusercontent.com/73652197/122344514-2aa4c080-cf47-11eb-8ac9-dcc8cfd57c8a.png)
so I decided not to add it :-)
