### ISSUE TITLE
unexpected panic while loading textures

### ISSUE THREAD

**Issue by gucio321** [AllenDang/giu#222]
hi,
I was testing something else and noticed the following behavior:
<details><summary>code</summary>

```golang
package main

import (
	"fmt"
	_ "image/jpeg"
	_ "image/png"
	"time"

	"github.com/AllenDang/giu"
	g "github.com/AllenDang/giu"
)

var rgba *giu.Texture

func loop() {
	g.SingleWindow().Layout(
		g.Label("Display image from rgba"),
		g.ImageButton(rgba).Size(200, 100),

		g.Label("Display image from file"),
		g.ImageWithFile("gopher.png").Size(300, 200),

		g.Label("Display image from url (wait few seconds to download)"),
		g.ImageWithUrl("https://png.pngitem.com/pimgs/s/3-36108_gopher-golang-hd-png-download.png").Size(300, 200),

		g.Label("Display images from url with loading and fallback"),
		g.ImageWithUrl(
			"https://png.pngitem.com/pimgs/s/424-4241958_transparent-gopher-png-golang-gopher-png-png-download.png").
			Timeout(5*time.Second).
			Size(300, 200).
			LayoutForLoading(
				g.Child().Size(300, 200).Layout(g.Layout{
					g.Label("Loading..."),
				}),
			).
			LayoutForFailure(
				g.ImageWithFile("./fallback.png").Size(300, 200),
			).
			OnReady(func() {
				fmt.Println("Image is downloaded.")
			}),

		g.Label("Handle failure event"),
		g.ImageWithUrl("http://x.y/z.jpg").Timeout(2*time.Second).OnFailure(func(err error) {
			fmt.Printf("Failed to download image, Error msg is %s\n", err.Error())
		}),

		g.Label("Display image from url without placeholder (no size when loading)"),
		g.ImageWithUrl("https://www.pngitem.com/pimgs/m/424-4242405_go-lang-gopher-clipart-png-download-golang-gopher.png").Size(300, 200),

		g.Label("Footer"),
	)
}

func main() {
	img, _ := g.LoadImage("./fallback.png")
	rgba, _ = g.NewTextureFromRgba(img)

	wnd := g.NewMasterWindow("Load Image", 600, 500, g.MasterWindowFlagsNotResizable)
	wnd.Run(loop)
}
```

</details>
<details><summary>panic message</summary>

```console
panic: mainthread: did not call Run

goroutine 1 [running, locked to thread]:
github.com/faiface/mainthread.checkRun(...)
	/home/user/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:24
github.com/faiface/mainthread.CallVal(0xc000013df0, 0xc000013df0, 0xc000068d40)
	/home/user/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:81 +0x146
github.com/AllenDang/giu.NewTextureFromRgba(0xc000068d40, 0xe, 0xc000068d40, 0x0)
	/home/user/git/d2/me/giu/Texture.go:26 +0x65
main.main()
	/home/user/git/d2/me/giu/examples/loadimage/loadimage.go:57 +0x48
exit status 2
```

</details>

do I need to load textures inside of loop func?

**Comment by AllenDang** [comment]
@gucio321 You should invoke giu.NewTextureFromRgba from another thread.

**Comment by gucio321** [comment]
fair enough
