### ISSUE TITLE
style: StyleVarItemSpacing crashes?

### ISSUE THREAD

**Issue by gucio321** [AllenDang/giu#318]
Hi there!
I'm getting a crash with imgui.PushStyleVar(StyleVarItemSpacing,0)
```golang
package main

import (
	"github.com/AllenDang/giu"
	"github.com/AllenDang/imgui-go"
)

func loop() {
	giu.SingleWindow().Layout(
		giu.Custom(func() {
			imgui.PushStyleVarFloat(imgui.StyleVarItemSpacing, 0)
			giu.Button("button 1").Build()
			giu.Button("button 2").Build()
			imgui.PopStyleVar()
		}),
	)
}

func main() {
	wnd := giu.NewMasterWindow("style bug", 640, 480, 0)
	wnd.Run(loop)
}
```

with StyleSetter it crashes too

**Comment by gucio321** [comment]
oh, I forgot, the panic message:
```console
main: imgui.cpp:2581: void ImGui::PushStyleVar(ImGuiStyleVar, float): Assertion `0 && "Called PushStyleVar() float variant but variable is not a float!"' failed.
SIGABRT: abort
PC=0x7f9b021f92a2 m=0 sigcode=18446744073709551610
signal arrived during cgo execution
```

**Comment by AllenDang** [comment]
@gucio321 Check the comment of StyleVarItemSpacing, it requires a Vec2, not a float, use PushStyleVarVec2

**Comment by gucio321** [comment]
@allenDang thank you very much. I tought, that I met this bug with vec2...

**Comment by gucio321** [comment]
well, but styleSetter still crashes:
```golang
package main

import (
	"github.com/AllenDang/giu"
)

func loop() {
	giu.SingleWindow().Layout(
		giu.Style().SetStyle(giu.StyleVarItemSpacing, 0, 0).To(
			giu.Button("button 1"),
			giu.Button("button 2"),
		),
	)
}

func main() {
	wnd := giu.NewMasterWindow("style bug", 640, 480, 0)
	wnd.Run(loop)
}
```

**Comment by gucio321** [comment]
@AllenDang seems like setstyle example crashes to me too.
<details><summary>stack trace</summary>

```console
setstyle: imgui.cpp:2595: void ImGui::PushStyleVar(ImGuiStyleVar, const ImVec2&): Assertion `0 && "Called PushStyleVar() ImVec2 variant but variable is not a ImVec2!"' failed.
SIGABRT: abort
PC=0x7fb1881cf2a2 m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x626300, 0xc0000cbb80, 0xc0000aa7b0)
	/usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc0000cbb50 sp=0xc0000cbb18 pc=0x48667b
github.com/AllenDang/imgui-go._Cfunc_iggPushStyleVarVec2(0xc00000000a, 0xc0000b2d78)
	_cgo_gotypes.go:5105 +0x3c fp=0xc0000cbb80 sp=0xc0000cbb50 pc=0x57e25c
github.com/AllenDang/imgui-go.PushStyleVarVec2(0xa, 0x4120000041200000)
	/home/user/go/pkg/mod/github.com/!allen!dang/imgui-go@v1.12.1-0.20210831132008-ff26a21b4e5b/imgui.go:247 +0x5d fp=0xc0000cbba8 sp=0xc0000cbb80 pc=0x58189d
github.com/AllenDang/giu.(*StyleSetter).Build(0xc0000e6a80)
	/home/user/git/d2/me/giu/Style.go:334 +0x19d fp=0xc0000cbc98 sp=0xc0000cbba8 pc=0x621e5d
github.com/AllenDang/giu.Layout.Build(0xc0000b5500, 0x4, 0x6)
	/home/user/git/d2/me/giu/Layout.go:17 +0x6b fp=0xc0000cbcc0 sp=0xc0000cbc98 pc=0x6203eb
github.com/AllenDang/giu.(*WindowWidget).Layout(0xc0000e6a00, 0xc0000b5500, 0x4, 0x6)
	/home/user/git/d2/me/giu/Window.go:117 +0x217 fp=0xc0000cbd28 sp=0xc0000cbcc0 pc=0x622557
main.loop()
	/home/user/git/d2/me/giu/examples/setstyle/setstyle.go:10 +0x41f fp=0xc0000cbdc0 sp=0xc0000cbd28 pc=0x62357f
github.com/AllenDang/giu.(*MasterWindow).render(0xc00007c000)
	/home/user/git/d2/me/giu/MasterWindow.go:190 +0xa9 fp=0xc0000cbe30 sp=0xc0000cbdc0 pc=0x6218a9
github.com/AllenDang/giu.(*MasterWindow).run.func1()
	/home/user/git/d2/me/giu/MasterWindow.go:208 +0x59 fp=0xc0000cbe70 sp=0xc0000cbe30 pc=0x622ad9
github.com/faiface/mainthread.Call.func1()
	/home/user/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:63 +0x2f fp=0xc0000cbea0 sp=0xc0000cbe70 pc=0x588e4f
github.com/faiface/mainthread.Run(0xc00000e3c0)
	/home/user/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:44 +0xb1 fp=0xc0000cbf28 sp=0xc0000cbea0 pc=0x588bd1
github.com/AllenDang/giu.(*MasterWindow).Run(0xc00007c000, 0x8dd748)
	/home/user/git/d2/me/giu/MasterWindow.go:278 +0x65 fp=0xc0000cbf48 sp=0xc0000cbf28 pc=0x621b45
main.main()
	/home/user/git/d2/me/giu/examples/setstyle/setstyle.go:28 +0x67 fp=0xc0000cbf88 sp=0xc0000cbf48 pc=0x6236c7
runtime.main()
	/usr/local/go/src/runtime/proc.go:225 +0x256 fp=0xc0000cbfe0 sp=0xc0000cbf88 pc=0x4bb1b6
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0000cbfe8 sp=0xc0000cbfe0 pc=0x4ecdc1

goroutine 5 [chan receive]:
github.com/faiface/mainthread.Call(0xc00009d9b0)
	/home/user/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:66 +0xc5
github.com/AllenDang/giu.(*MasterWindow).run(0xc00007c000)
	/home/user/git/d2/me/giu/MasterWindow.go:206 +0xa5
github.com/AllenDang/giu.(*MasterWindow).Run.func1()
	/home/user/git/d2/me/giu/MasterWindow.go:283 +0x4d
github.com/faiface/mainthread.Run.func1(0xc00000e3c0, 0xc000024060)
	/home/user/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:37 +0x27
created by github.com/faiface/mainthread.Run
	/home/user/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:36 +0xa5

rax    0x0
rbx    0x7fb188045740
rcx    0x7fb1881cf2a2
rdx    0x0
rdi    0x2
rsi    0x7fff45a62590
rbp    0x7fb1883578f0
rsp    0x7fff45a62590
r8     0x0
r9     0x7fff45a62590
r10    0x8
r11    0x246
r12    0x9174b2
r13    0xa23
r14    0x919260
r15    0xffffffffffffffff
rip    0x7fb1881cf2a2
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
exit status 2
```

</details>

**Comment by AllenDang** [comment]
@gucio321 Yes, it's a bug and it is fixed.

**Comment by gucio321** [comment]
Yah, @AllenDang it is fixed, but I'm wondering what was the bug :grinning:
I see, that you changed enum layout to use `iota` in https://github.com/AllenDang/giu/commit/176300f5c4c07ae4af56ad65f0e442a3806bb9ec but... what was exactly happend :confused:

**Comment by gucio321** [comment]
well, I think that i can blame https://github.com/AllenDang/imgui-go/commit/c6813f114e7eb9732faeee1616aa62d0b14786eb .
What about the following solution to avoid such the crashes in the future?:
```golang
type StyleVarID imgui.StyleVarID

const (
      StyleVarAlpha StyleVarID = imgui.StyleVarAlpha
      // e.t.c.
)
```

thenn, if you add something in imgui, you need to manually add it in giu.

**Comment by AllenDang** [comment]
@gucio321 Yes, agree. We should do it in both imgui-go and giu, imgui <-> imgui-go <-> giu, name by name.

**Comment by gucio321** [comment]
@AllenDang there is a bug:
when pushing Style().SetStyle with StyleVarID of type float, imgui panics.
