### ISSUE TITLE
Too many vertices in ImDrawList using 16-bit indices. 

### ISSUE THREAD

**Issue by daiwhea** [AllenDang/giu#374]
I'm using giu to draw stock chart. And now I got some crashes like below. I'm not sure how to reproduce it, and I can't make a demo to show it to you because the stock day chart data is to big to share. So there is just some crash log. Wish it could help a little.

```
Assertion failed: (draw_list->_VtxCurrentIdx < (1 << 16) && "Too many vertices in ImDrawList using 16-bit indices. Read comment above"), function AddDrawListToDrawData, file imgui.cpp, line 4349.
SIGABRT: abort
PC=0x7fff5542ab66 m=0 sigcode=0
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x43ab880, 0xc001129dc0, 0x0)
	/usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc001129d90 sp=0xc001129d58 pc=0x400517b
github.com/AllenDang/imgui-go._Cfunc_iggRender()
	_cgo_gotypes.go:5159 +0x3c fp=0xc001129dc0 sp=0xc001129d90 pc=0x41232bc
github.com/AllenDang/imgui-go.Render(...)
	/Users/daiwhea/go/pkg/mod/github.com/!allen!dang/imgui-go@v1.12.1-0.20210929095526-68b309906bdc/imgui.go:36
github.com/AllenDang/giu.(*MasterWindow).render(0xc000122000)
	/Users/daiwhea/go/pkg/mod/github.com/gucio321/giu@v0.5.3-0.20211004080722-00c323bfdb3d/MasterWindow.go:193 +0xaf fp=0xc001129e30 sp=0xc001129dc0 pc=0x42e0bcf
github.com/AllenDang/giu.(*MasterWindow).run.func1()
	/Users/daiwhea/go/pkg/mod/github.com/gucio321/giu@v0.5.3-0.20211004080722-00c323bfdb3d/MasterWindow.go:210 +0x59 fp=0xc001129e70 sp=0xc001129e30 pc=0x42e84b9
github.com/faiface/mainthread.Call.func1()
	/Users/daiwhea/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:63 +0x2f fp=0xc001129ea0 sp=0xc001129e70 pc=0x413160f
github.com/faiface/mainthread.Run(0xc0001204b0)
	/Users/daiwhea/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:44 +0xb1 fp=0xc001129f28 sp=0xc001129ea0 pc=0x4131391
github.com/AllenDang/giu.(*MasterWindow).Run(0xc000122000, 0x4772678)
	/Users/daiwhea/go/pkg/mod/github.com/gucio321/giu@v0.5.3-0.20211004080722-00c323bfdb3d/MasterWindow.go:283 +0x65 fp=0xc001129f48 sp=0xc001129f28 pc=0x42e0f05
main.main()
	/Users/daiwhea/myworks/daiwhea/ImStock/ImStock.go:212 +0xbf fp=0xc001129f88 sp=0xc001129f48 pc=0x43a797f
runtime.main()
	/usr/local/go/src/runtime/proc.go:225 +0x256 fp=0xc001129fe0 sp=0xc001129f88 pc=0x4039bb6
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc001129fe8 sp=0xc001129fe0 pc=0x406cd21

goroutine 18 [chan receive]:
github.com/faiface/mainthread.Call(0xc000ee4660)
	/Users/daiwhea/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:66 +0xc5
github.com/AllenDang/giu.(*MasterWindow).run(0xc000122000)
	/Users/daiwhea/go/pkg/mod/github.com/gucio321/giu@v0.5.3-0.20211004080722-00c323bfdb3d/MasterWindow.go:208 +0xa5
github.com/AllenDang/giu.(*MasterWindow).Run.func1()
	/Users/daiwhea/go/pkg/mod/github.com/gucio321/giu@v0.5.3-0.20211004080722-00c323bfdb3d/MasterWindow.go:288 +0x4d
github.com/faiface/mainthread.Run.func1(0xc0001204b0, 0xc000126000)
	/Users/daiwhea/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:37 +0x27
created by github.com/faiface/mainthread.Run
	/Users/daiwhea/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:36 +0xa5

rax    0x0
rbx    0x7fff8d9de380
rcx    0x7ffeefbff358
rdx    0x0
rdi    0x307
rsi    0x6
rbp    0x7ffeefbff390
rsp    0x7ffeefbff358
r8     0x0
r9     0x0
r10    0x0
r11    0x206
r12    0x307
r13    0x2d7b7000
r14    0x6
r15    0x2d
rip    0x7fff5542ab66
rflags 0x206
cs     0x7
fs     0x0
gs     0x0
exit status 2
```

And this is my go.mod file
```
module daiwhea.com/gostock

go 1.16

require (
	github.com/360EntSecGroup-Skylar/excelize/v2 v2.4.0
	github.com/AllenDang/giu v0.5.7-0.20210930062057-7a1a262cf0eb
	github.com/AllenDang/imgui-go v1.12.1-0.20210929095526-68b309906bdc
	github.com/atotto/clipboard v0.1.4
	github.com/go-resty/resty/v2 v2.6.0 // indirect
	github.com/sqweek/dialog v0.0.0-20210702151303-c326b49d3f01
	golang.org/x/net v0.0.0-20210929193557-e81a3d93ecf6 // indirect
	golang.org/x/text v0.3.6
)

replace github.com/AllenDang/giu => github.com/gucio321/giu v0.5.3-0.20211004080722-00c323bfdb3d
```

It crashes when I switch to show other stock chart. But it won't crash every time when I switch stock. And I don't know when will it crash.

Thanks for your time.

**Comment by daiwhea** [comment]
Is there any limits for items painted in one loop? It will show a lot of lines/points/rects.

**Comment by gucio321** [comment]
in imgui.cpp we can read:
```c++
    // Check that draw_list doesn't use more vertices than indexable (default ImDrawIdx = unsigned short = 2 bytes = 64K vertices per ImDrawList = per window)
    // If this assert triggers because you are drawing lots of stuff manually:
    // - First, make sure you are coarse clipping yourself and not trying to draw many things outside visible bounds.
    //   Be mindful that the ImDrawList API doesn't filter vertices. Use the Metrics/Debugger window to inspect draw list contents.
    // - If you want large meshes with more than 64K vertices, you can either:
    //   (A) Handle the ImDrawCmd::VtxOffset value in your renderer backend, and set 'io.BackendFlags |= ImGuiBackendFlags_RendererHasVtxOffset'.
    //       Most example backends already support this from 1.71. Pre-1.71 backends won't.
    //       Some graphics API such as GL ES 1/2 don't have a way to offset the starting vertex so it is not supported for them.
    //   (B) Or handle 32-bit indices in your renderer backend, and uncomment '#define ImDrawIdx unsigned int' line in imconfig.h.
    //       Most example backends already support this. For example, the OpenGL example code detect index size at compile-time:
    //         glDrawElements(GL_TRIANGLES, (GLsizei)pcmd->ElemCount, sizeof(ImDrawIdx) == 2 ? GL_UNSIGNED_SHORT : GL_UNSIGNED_INT, idx_buffer_offset);
    //       Your own engine or render API may use different parameters or function calls to specify index sizes.
    //       2 and 4 bytes indices are generally supported by most graphics API.
    // - If for some reason neither of those solutions works for you, a workaround is to call BeginChild()/EndChild() before reaching
    //   the 64K limit to split your draw commands in multiple draw lists.
```

**Comment by daiwhea** [comment]
@gucio321 Thanks, I really haven't read it before.

**Comment by daiwhea** [comment]
@gucio321 Seems giu hasn't provide  BeginChild()/EndChild() ? How can I achieve this?

Thanks !!!

**Comment by gucio321** [comment]
@daiwhea lets look how is it done in examples/widgets: https://github.com/AllenDang/giu/blob/7a1a262cf0eb925dd66f6604d724506ba32023e0/examples/widgets/widgets.go#L233

you don't even need to Begin/End anything in giu. it is done automatically by `Build()` methods of the widgets.
to use child, you just do `g.Child().Layout(/*everything here will be rendered inside of imgui child*/)`

**Comment by daiwhea** [comment]
@gucio321 OK, I'll use g.Child() to place some items. Thanks

**Comment by daiwhea** [comment]
I'm sorry, I didn't expressed my issue clearly. I just use canvas to paint lots of lines/rectangles/circles. So I haven't use Layout() at all. 

Will g.Child() work for this?

**Comment by gucio321** [comment]
hmm, idk, if it works in native imgui, it should work in giu too.
You just need to use giu.Custom(...) and put you canvas there

**Comment by daiwhea** [comment]
No, seems this doesn't work. Please see code below, I add g.Custom() for each loop. But It still crashed whether has or hasn't g.Custom().

```go
		for i, tf := range rps.TimeFrames {
			// 对应tf需要展示
			if tfs[i] {
				g.Custom(func() {
					p0, _ := s.getPoint(tf, s.leftIndex)
					for i := s.leftIndex + 1; i < s.rightIndex; i += 1 {
						p1, _ := s.getPoint(tf, i)
						if p0.Y > 0 {
							canvas.AddLine(p0, p1, tfColors[tf], 1)
						}
						p0 = p1
					}
				}).Build()
			}
		}
```

**Comment by gucio321** [comment]
@daiwhea I meant, that you need to put giu.CustomWidget inside of g.Child().Layout
e.g.:
```golang
g.Child().Layout(
g.Custom(func() {
      		for i, tf := range rps.TimeFrames {
			// 对应tf需要展示
			if tfs[i] {
					p0, _ := s.getPoint(tf, s.leftIndex)
					for i := s.leftIndex + 1; i < s.rightIndex; i += 1 {
						p1, _ := s.getPoint(tf, i)
						if p0.Y > 0 {
							canvas.AddLine(p0, p1, tfColors[tf], 1)
						}
						p0 = p1
					}
			}
		}
}),
),
```

**Comment by daiwhea** [comment]
@gucio321 Thanks. It works.
