### ISSUE TITLE
how to run imgui function in another goroutine?

### ISSUE THREAD

**Issue by gucio321** [AllenDang/giu#409]
### What happend?

Hi!
I've an issue while trying to run `GetAvailableRegion` in a separated goroutine.
The panic says:
```console
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x178 pc=0x61f1a1]

runtime stack:
runtime.throw({0x889c5d, 0x7fa5b753ed70})
	/usr/local/go/src/runtime/panic.go:1198 +0x71
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:719 +0x396

goroutine 3 [syscall]:
runtime.cgocall(0x5e67b0, 0xc000041790)
	/usr/local/go/src/runtime/cgocall.go:156 +0x5c fp=0xc000041768 sp=0xc000041730 pc=0x486fbc
github.com/AllenDang/imgui-go._Cfunc_iggContentRegionAvail(0xc000180000)
	_cgo_gotypes.go:1303 +0x45 fp=0xc000041790 sp=0xc000041768 pc=0x54fca5
github.com/AllenDang/imgui-go.ContentRegionAvail()
	/home/username/git/d2/me/giu/vendor/github.com/AllenDang/imgui-go/imgui.go:147 +0x7c fp=0xc0000417d0 sp=0xc000041790 pc=0x557adc
github.com/AllenDang/giu.GetAvailableRegion(...)
	/home/username/git/d2/me/giu/Utils.go:125
main.loop.func1()
	/home/username/git/d2/me/giu/examples/bug-408/main.go:9 +0x18 fp=0xc0000417e0 sp=0xc0000417d0 pc=0x5e4938
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0000417e8 sp=0xc0000417e0 pc=0x4e49c1
created by main.loop
	/home/username/git/d2/me/giu/examples/bug-408/main.go:8 +0x26

goroutine 1 [runnable, locked to thread]:
github.com/go-gl/gl/v3.2-core/gl._Cfunc_glowBindBuffer(0x7fa5dea43660, 0x8893, 0x2)
	_cgo_gotypes.go:2983 +0x45
github.com/go-gl/gl/v3.2-core/gl.BindBuffer(...)
	/home/username/git/d2/me/giu/vendor/github.com/go-gl/gl/v3.2-core/gl/package.go:8720
github.com/AllenDang/imgui-go.(*OpenGL3).Render(0xc000094320, {0x44200000, 0x43f00000}, {0x44200000, 0x43f00000}, 0xc0000d5e08)
	/home/username/git/d2/me/giu/vendor/github.com/AllenDang/imgui-go/RendererOpenGL3.go:179 +0xbce
github.com/AllenDang/giu.(*MasterWindow).render(0xc000117490)
	/home/username/git/d2/me/giu/MasterWindow.go:205 +0x124
github.com/AllenDang/giu.(*MasterWindow).run.func1()
	/home/username/git/d2/me/giu/MasterWindow.go:220 +0x48
github.com/faiface/mainthread.Call.func1()
	/home/username/git/d2/me/giu/vendor/github.com/faiface/mainthread/mainthread.go:63 +0x26
github.com/faiface/mainthread.Run(0xc0000af2f0)
	/home/username/git/d2/me/giu/vendor/github.com/faiface/mainthread/mainthread.go:44 +0xc9
github.com/AllenDang/giu.(*MasterWindow).Run(0xc000117490, 0x891b58)
	/home/username/git/d2/me/giu/MasterWindow.go:294 +0x72
main.main()
	/home/username/git/d2/me/giu/examples/bug-408/main.go:19 +0x3d

goroutine 21 [chan receive]:
github.com/faiface/mainthread.Call(0xc000070030)
	/home/username/git/d2/me/giu/vendor/github.com/faiface/mainthread/mainthread.go:66 +0xb1
github.com/AllenDang/giu.(*MasterWindow).run(0xc000117490)
	/home/username/git/d2/me/giu/MasterWindow.go:218 +0x87
github.com/AllenDang/giu.(*MasterWindow).Run.func1()
	/home/username/git/d2/me/giu/MasterWindow.go:299 +0x4b
github.com/faiface/mainthread.Run.func1()
	/home/username/git/d2/me/giu/vendor/github.com/faiface/mainthread/mainthread.go:37 +0x26
created by github.com/faiface/mainthread.Run
	/home/username/git/d2/me/giu/vendor/github.com/faiface/mainthread/mainthread.go:36 +0xbd
exit status 2
```

### Code example

Here is a minimal example! Of course my real code is much more complicated!
<details><summary><code>main.go</code></summary>

```golang
package main

import (
	"github.com/AllenDang/giu"
)

func loop() {
	go func() {
                // this causes crash. What to do instead?
		_, _ = giu.GetAvailableRegion()
	}()

	giu.SingleWindow().Layout(
		giu.Label("Hello World"),
	)
}

func main() {
	wnd := giu.NewMasterWindow("issue 409 [bug]", 640, 480, 0)
	wnd.Run(loop)
}

```

</details>

### To Reproduce

1. Run my demo
2. will see panic

### Version

master

### OS

Fedora 34

**Comment by AllenDang** [comment]
@gucio321 Normally, I will do like this, but seems doesn't work for GetAvailableRegion.
```go
func callFnAsync() {
	go func() {
		mainthread.Call(func() {
			w, h := giu.GetAvailableRegion()
			fmt.Println(w, h)
		})
	}()
}
```

**Comment by gucio321** [comment]
@allenDang seems so... do you know any solution?

**Comment by gucio321** [comment]
In my opinion this panic doesn't look like first-hand error... It seems to come from mainthread internal error/crash which was not reported correctly so that it is hard to debug?...

**Comment by AllenDang** [comment]
I don't think it's a defect of mainthread, because it's code is pretty simple and straight forward. It's more related to the internal state of imgui. I suggest to change a solution. It might not be necessary to run it in goroutine.

**Comment by gucio321** [comment]
well, so let me explain, what I'm exactly trying to do (maybe there is easier solution).
Im trying to implement images from url in markdown implementation.
Also the current implemetation leaves much to be desired. In fact while the markdown image is loaded, mainthread is paused what shouldn't happen any time. I'm going to go ahead and allow imgui-go to run image callback in goroutine.
And now appears the problemm - In current implementation is there a step which allows to auto-scale image to make it not larger than the available region: https://github.com/AllenDang/giu/blob/55124a376e0e727df7439baffcbcf3de061bd5c2/Markdown.go#L68

**Comment by AllenDang** [comment]
@gucio321 One solution is, save available region to variables on every frame, and use it later.

**Comment by gucio321** [comment]
sadly it is not possible.
please take a look here: https://github.com/gucio321/giu/tree/markdown-image-from-url
gui-side callback is called only once by imgui in a separated goroutine and it is supposed to do the whole work.
Do you have any idea to bypass this panic?

**Comment by AllenDang** [comment]
@AllenDang I have some thoughts, testing now, feedback to you later.

**Comment by AllenDang** [comment]
@gucio321 I got a success try. `GetAvailableRegion` has to be called between imgui.BeginFrame() and EndFrame(), so if the requirement is `to get available content size from goroutine`, you could try this solution:
```go
package main

import (
	"fmt"

	g "github.com/AllenDang/giu"
)

var (
	asyncTrigger  bool
	width, height float32
)

func onAsync() {
	go func() {
		// Trigger imgui function from goroutine
		asyncTrigger = true

		// Refresh the draw loop to execte imgui function
		g.Update()

		// Retrive result
		fmt.Println(width, height)
	}()
}

func loop() {
	g.SingleWindow().Layout(
		g.Button("Run async").OnClick(onAsync),
		g.Custom(func() {
			if asyncTrigger {
				width, height = g.GetAvailableRegion()
				asyncTrigger = false
			}
		}),
	)
}

func main() {
	wnd := g.NewMasterWindow("Hello world", 400, 200, 0)
	wnd.Run(loop)
}

```

**Comment by gucio321** [comment]
yah, I just realised that calling GetAvailableRegion exactly from goroutine doesn't make sense at all, because it returns cursor position *exactly* at the moment when goroutine calls it so it may be any rendering moment.
