### ISSUE TITLE
Need help for ListClipper

### ISSUE THREAD

**Issue by daiwhea** [AllenDang/giu#505]
I updated giu from giu@v0.5.7-0.20211021021654-1a18181287fc to v0.6.2 . Some codes using ListClipper crashed. I can't figure out the reason. Would you please have a look? Thanks for your time.

```
package main

import (
  "fmt"

  g "github.com/AllenDang/giu"
  "github.com/AllenDang/imgui-go"
)

type ListBoxState struct {
  selectedIndex int
}

func (s *ListBoxState) Dispose() {
  // Nothing to do here.
}

type ListBoxWidget struct {
  id      string
  width   float32
  height  float32
  border  bool
  items   []string
  onClick func(selectedIndex int)
  onMenu  func(selectedIndex int, menu string)
}

func ListBox(id string, items []string) *ListBoxWidget {
  return &ListBoxWidget{
    id:      id,
    width:   0,
    height:  0,
    border:  true,
    items:   items,
    onClick: nil,
    onMenu:  nil,
  }
}

func (l *ListBoxWidget) Size(width, height float32) *ListBoxWidget {
  var scale float32 = 1 //g.Context.GetPlatform().GetContentScale()
  l.width, l.height = width*scale, height*scale
  return l
}

func (l *ListBoxWidget) Border(b bool) *ListBoxWidget {
  l.border = b
  return l
}

func (l *ListBoxWidget) OnClick(onClick func(selectedIndex int)) *ListBoxWidget {
  l.onClick = onClick
  return l
}

func (l *ListBoxWidget) Build() {
  var state *ListBoxState
  if s := g.Context.GetState(l.id); s == nil {
    state = &ListBoxState{selectedIndex: 0}
    g.Context.SetState(l.id, state)
  } else {
    state = s.(*ListBoxState)
  }

  child := g.Child().Border(l.border).Size(l.width, l.height).Layout(g.Layout{
    g.Custom(func() {
      var clipper imgui.ListClipper
      clipper.Begin(len(l.items))

      for clipper.Step() {
        for i := clipper.DisplayStart(); i < clipper.DisplayEnd(); i++ {
          selected := i == state.selectedIndex
          item := l.items[i]

          g.Selectable(item).Selected(selected).OnClick(func() {
            state.selectedIndex = i
            if l.onClick != nil {
              l.onClick(i)
            }
          }).Build()
        }
      }

      clipper.End()
    }),
  })

  child.Build()
}

func loop() {
  g.SingleWindow().Layout(
    ListBox("test", []string{"aaa", "bbb", "c", "ddd", "e"}).OnClick(func(selectedIndex int) {
      fmt.Println("selected", selectedIndex)
    }).Size(102, 200),
  )
}

func main() {
  wnd := g.NewMasterWindow("Custom Widget", 400, 300, g.MasterWindowFlagsNotResizable)
  wnd.Run(loop)
}
```

Error Msgs:
```
run stock/main.go
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x41aa2a4]

runtime stack:
runtime.throw({0x4492333?, 0x41c121b?})
	/usr/local/go/src/runtime/panic.go:992 +0x71
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:802 +0x3a9

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x41761c0, 0xc0001c3ab8)
	/usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc0001c3a90 sp=0xc0001c3a58 pc=0x40043dc
github.com/AllenDang/imgui-go._Cfunc_iggListClipperBegin(0x0, 0x5, 0xbf800000)
	_cgo_gotypes.go:4819 +0x45 fp=0xc0001c3ab8 sp=0xc0001c3a90 pc=0x40d7525
github.com/AllenDang/imgui-go.(*ListClipper).BeginV.func1(0x40d4465?, 0x5, 0xbf800000)
	/Users/daiwhea/go/pkg/mod/github.com/!allen!dang/imgui-go@v1.12.1-0.20220322114136-499bbf6a42ad/ListClipper.go:71 +0x5d fp=0xc0001c3af0 sp=0xc0001c3ab8 pc=0x40dc7fd
github.com/AllenDang/imgui-go.(*ListClipper).BeginV(0x40dcd3a?, 0x50709b0?, 0x50709b0?)
	/Users/daiwhea/go/pkg/mod/github.com/!allen!dang/imgui-go@v1.12.1-0.20220322114136-499bbf6a42ad/ListClipper.go:71 +0x19 fp=0xc0001c3b18 sp=0xc0001c3af0 pc=0x40dc759
github.com/AllenDang/imgui-go.(*ListClipper).Begin(...)
	/Users/daiwhea/go/pkg/mod/github.com/!allen!dang/imgui-go@v1.12.1-0.20220322114136-499bbf6a42ad/ListClipper.go:60
main.(*ListBoxWidget).Build.func1()
	/Users/daiwhea/myworks/daiwhea/ImStock/examples/stock/main.go:68 +0x49 fp=0xc0001c3b78 sp=0xc0001c3b18 pc=0x4174349
github.com/AllenDang/giu.(*CustomWidget).Build(0xc000000001?)
	/Users/daiwhea/go/pkg/mod/github.com/!allen!dang/giu@v0.6.2/ExtraWidgets.go:310 +0x1f fp=0xc0001c3b88 sp=0xc0001c3b78 pc=0x417083f
github.com/AllenDang/giu.Layout.Build(...)
	/Users/daiwhea/go/pkg/mod/github.com/!allen!dang/giu@v0.6.2/Layout.go:28
github.com/AllenDang/giu.(*Layout).Build(0xc000264708?)
	<autogenerated>:1 +0x78 fp=0xc0001c3bb8 sp=0xc0001c3b88 pc=0x4173d18
github.com/AllenDang/giu.Layout.Build(...)
	/Users/daiwhea/go/pkg/mod/github.com/!allen!dang/giu@v0.6.2/Layout.go:28
github.com/AllenDang/giu.(*ChildWidget).Build(0xc0001da440)
	/Users/daiwhea/go/pkg/mod/github.com/!allen!dang/giu@v0.6.2/Widgets.go:75 +0xa2 fp=0xc0001c3c08 sp=0xc0001c3bb8 pc=0x4173462
main.(*ListBoxWidget).Build(0xc00019e370)
	/Users/daiwhea/myworks/daiwhea/ImStock/examples/stock/main.go:88 +0x25e fp=0xc0001c3c80 sp=0xc0001c3c08 pc=0x41742be
github.com/AllenDang/giu.Layout.Build(...)
	/Users/daiwhea/go/pkg/mod/github.com/!allen!dang/giu@v0.6.2/Layout.go:28
github.com/AllenDang/giu.(*WindowWidget).Layout(0xc0001da400, {0xc0001c3d40?, 0x1, 0x1})
	/Users/daiwhea/go/pkg/mod/github.com/!allen!dang/giu@v0.6.2/Window.go:140 +0x29b fp=0xc0001c3d10 sp=0xc0001c3c80 pc=0x417397b
main.loop()
	/Users/daiwhea/myworks/daiwhea/ImStock/examples/stock/main.go:92 +0x167 fp=0xc0001c3d60 sp=0xc0001c3d10 pc=0x4174727
github.com/AllenDang/giu.(*MasterWindow).render(0xc0000ba000)
	/Users/daiwhea/go/pkg/mod/github.com/!allen!dang/giu@v0.6.2/MasterWindow.go:213 +0x13c fp=0xc0001c3df0 sp=0xc0001c3d60 pc=0x417241c
github.com/AllenDang/giu.(*MasterWindow).run.func1()
	/Users/daiwhea/go/pkg/mod/github.com/!allen!dang/giu@v0.6.2/MasterWindow.go:238 +0x6d fp=0xc0001c3e80 sp=0xc0001c3df0 pc=0x417270d
github.com/faiface/mainthread.Call.func1()
	/Users/daiwhea/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:63 +0x26 fp=0xc0001c3eb0 sp=0xc0001c3e80 pc=0x4169506
github.com/faiface/mainthread.Run(0xc0000b64c8)
	/Users/daiwhea/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:44 +0xc4 fp=0xc0001c3f28 sp=0xc0001c3eb0 pc=0x41692c4
github.com/AllenDang/giu.(*MasterWindow).Run(0xc0000ba000, 0x449a058)
	/Users/daiwhea/go/pkg/mod/github.com/!allen!dang/giu@v0.6.2/MasterWindow.go:312 +0x72 fp=0xc0001c3f48 sp=0xc0001c3f28 pc=0x4172892
main.main()
	/Users/daiwhea/myworks/daiwhea/ImStock/examples/stock/main.go:101 +0x45 fp=0xc0001c3f80 sp=0xc0001c3f48 pc=0x4174785
runtime.main()
	/usr/local/go/src/runtime/proc.go:250 +0x212 fp=0xc0001c3fe0 sp=0xc0001c3f80 pc=0x4035b92
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0001c3fe8 sp=0xc0001c3fe0 pc=0x4061161

goroutine 50 [chan receive]:
github.com/faiface/mainthread.Call(0xc000182f60)
	/Users/daiwhea/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:66 +0xb1
github.com/AllenDang/giu.(*MasterWindow).run(0xc0000ba000)
	/Users/daiwhea/go/pkg/mod/github.com/!allen!dang/giu@v0.6.2/MasterWindow.go:227 +0x87
github.com/AllenDang/giu.(*MasterWindow).Run.func1()
	/Users/daiwhea/go/pkg/mod/github.com/!allen!dang/giu@v0.6.2/MasterWindow.go:318 +0x56
github.com/faiface/mainthread.Run.func1()
	/Users/daiwhea/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:37 +0x26
created by github.com/faiface/mainthread.Run
	/Users/daiwhea/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:36 +0xb8
exit status 2
```

**Comment by gucio321** [comment]
@daiwhea please take a look how TableWidget is using list clipper.
IMO since new imgui release that mechanism got changed, so you need to change
```golang
var clipper imgui.ListClipper
```
into
```golang
clipper := imgui.NewListClipper()
defer clipper.Deelete()
```

**Comment by daiwhea** [comment]
> @daiwhea please take a look how TableWidget is using list clipper. IMO since new imgui release that mechanism got changed, so you need to change
> 
> ```go
> var clipper imgui.ListClipper
> ```
> 
> into
> 
> ```go
> clipper := imgui.NewListClipper()
> defer clipper.Deelete()
> ```

Yes, imgui.NewListClipper() does work. Thanks.

This is not a bug report or feature request. So let's close it now. Thank you.
