### ISSUE TITLE
Dynamically selecting between X11 and Wayland backend

### ISSUE THREAD

**Issue by Vendicated** [AllenDang/giu#686]
Using `--tags wayland`, it is possible to create a wayland binary

However, I haven't found a way to create one binary that will run on both x11 and wayland, dynamically selecting the correct backend.

Is there any good way to do so? It seems like go-glfw doesn't even let you specify both x11 and wayland tag at once

GLFW itself does seem to support this though, see https://github.com/glfw/glfw/commit/56a4cb0a3a2c7a44a2fd8ab3335adf915e19d30c

**Comment by gucio321** [comment]
@Vendicated I can't reproduce.
For me one giu binary works on both wayland and xorg

**Comment by Vendicated** [comment]
Apologies for the late reply, I'm only now looking into this again

Are you sure you're not just running the binary through XWayland?

For me, when compiling with `-tags wayland`, it will fail to open on X11 with
```
2023/12/25 00:49:35 PlatformError: Wayland: Failed to connect to display
panic: NotInitialized: The GLFW library is not initialized
```

When compiling without the tag, it will open in XWayland. Or, if you are not using XWayland, error with
```
2023/12/25 00:59:38 PlatformError: X11: The DISPLAY environment variable is missing
panic: NotInitialized: The GLFW library is not initialized
```

There is a [GLFW_PLATFORM hint](https://github.com/glfw/glfw/blob/b4c3ef9d0fdf46845f3e81e5d989dab06e71e6c1/include/GLFW/glfw3.h#L1299) you can set to wayland/x11, but [go-glfw doesn't seem to even have this code](https://github.com/search?q=repo%3Ago-gl%2Fglfw+%2F%5CbGLFW_PLATFORM%5Cb%2F&type=code). Does that mean it hasn't updated to have the above linked automatic platform selection commit?

I tried to hardcode the values in my code (`glfw.InitHint(0x00050003, 0x00060003)`) but it paniced with `panic: InvalidEnum: Invalid init hint 0x00050003`

I'm sorry if i'm missing anything. Help would be greatly appreciated

**Comment by gucio321** [comment]
Could you try with the latest code?
We're not using gogl glfw anymore

**Comment by Vendicated** [comment]
Oh I missed that. I did a `go get -u` but it didn't upgrade to that

Anyway, it's still failing without XWayland. Do i have to pass any specific build tags?

```
Glfw Error 65544: X11: The DISPLAY environment variable is missing
panic: Failed to initialize GLFW

goroutine 1 [running, locked to thread]:
github.com/AllenDang/cimgui-go.NewGLFWBackend(...)
	/home/vee/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20231219093052-24bd5dc22643/glfw_backend.go:201
github.com/AllenDang/giu.NewMasterWindow({0xd13a6a, 0x11}, 0x4b0, 0x320, 0xc000030000?)
	/home/vee/go/pkg/mod/github.com/!allen!dang/giu@v0.7.1-0.20231219095113-bf1aacdc1161/MasterWindow.go:88 +0x4ac
main.main()
	/home/vee/Coding/Installer/gui.go:70 +0x9c
```

(On a side note, Text is also really messed up but you might already be aware of this?)
![](https://github.com/AllenDang/giu/assets/45497981/102afb42-d45f-44c2-bffb-6427f5475720)

**Comment by gucio321** [comment]
Ok, let me check this

**Comment by gucio321** [comment]
> (On a side note, Text is also really messed up but you might already be aware of this?)

Yeah they're is something wrong with font atlas

**Comment by gucio321** [comment]
giu uses glfw v3.3.
TO support wayland we need v3.4+ which has however no full wayland support yet (I mean multiviewpor feature. see https://github.com/AllenDang/cimgui-go/pull/314).
Waiting for next glfw release then.

**Comment by LiEnby** [comment]
im getting the same 
``X11: The DISPLAY environment variable is missing`` error on wayland, but *only* if i run the program from inside a flatpak, it works fine outside one :?
