### ISSUE TITLE
codeeditor demo running panic

### ISSUE THREAD

**Issue by programClown** [AllenDang/giu#689]
error message
```
> go run .\main.go
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x7ff790be28ff]

goroutine 1 [running, locked to thread]:
github.com/AllenDang/giu.(*context).GetWidgetIndex(...)
        D:/Go/pkg/mod/github.com/!allen!dang/giu@v0.6.3-0.20230807193504-b8dd4052ada8/Context.go:167
github.com/AllenDang/giu.GenAutoID(...)
        D:/Go/pkg/mod/github.com/!allen!dang/giu@v0.6.3-0.20230807193504-b8dd4052ada8/Widgets.go:12 
github.com/AllenDang/giu.CodeEditor()
        D:/Go/pkg/mod/github.com/!allen!dang/giu@v0.6.3-0.20230807193504-b8dd4052ada8/CodeEditor.go:45 +0x1f
main.main()
        D:/Go/src/giu-demo/main.go:52 +0x3f
exit status 2
````

**Comment by gucio321** [comment]
thank you for your report. Will be fixed soon.
