### ISSUE TITLE
Exit Status

### ISSUE THREAD

**Issue by assaultful** [AllenDang/giu#74]
After trying to run some code with this GIU I got the exit status "exit status 3221225477", fyne seems to work fine so I'm not sure what is causing this issue with this GUI.

**Comment by AllenDang** [comment]
@assaultful Can you post the demo code?

**Comment by assaultful** [comment]
@AllenDang its my friends code that im tryna test to get into golang - its here https://pastebin.com/L7MC4STJ

**Comment by AllenDang** [comment]
@assaultful Sorry for the late response. One question, exit status 3221225477, do you mean cannot launch application normally and the return value is 3221225477? Or you mean everything works fine just got the return value after exit?

**Comment by assaultful** [comment]
I mean when I try and do go run main.go for example it just shows that exit value, if I compile to an exe it shows for a split second but then I assume shows the same exit value again

**Comment by AllenDang** [comment]
@assaultful I think this is not caused by giu itself. You may need to debug other part of the code.

**Comment by assaultful** [comment]
I have debugged the code and it works on another system

**Comment by yunfengwangluo** [comment]
Exception 0xc0000005 0x1 0x58581f3d 0xde4165
PC=0xde4165

runtime: unknown pc 0xde4165
stack: frame={sp:0x6d101ffa58, fp:0x0} stack=[0x0,0x6d101ffc70)
0000006d101ff958:  0000000000000061  0000000000000008 
0000006d101ff968:  0000000000de8a32  0000000000000001 
0000006d101ff978:  0000000000de5500  000000000000c000 
0000006d101ff988:  0000021d00000000  656d68732d636367 
0000006d101ff998:  6f2d326d64742d6d  626f6c675f65636e 
0000006d101ff9a8:  6d656d68735f6c61  616161616161612d 
0000006d101ff9b8:  6161616161616161  6161616161616161 
0000006d101ff9c8:  4141416161616141  6141416141614161 
0000006d101ff9d8:  6141416141616161  4141416161616161 
0000006d101ff9e8:  6161614161614161  0000000000000000 
0000006d101ff9f8:  0000000000000000  0000021d58580000 
0000006d101ffa08:  00000020c1aa73d4  0000021d58580000 
0000006d101ffa18:  0000000000ef6da0  0000000000debb40 
0000006d101ffa28:  000000c0000d7d18  0000000002030000 
0000006d101ffa38:  0000000000000000  0000000000000018 
0000006d101ffa48:  0000000000000007  0000006d101ffbf0 
0000006d101ffa58: <0000000000de438b  0000021d58580000 
0000006d101ffa68:  00007fffc1aa73d4  0000021d58580000 
0000006d101ffa78:  0000021d40000062  0000000000000001 
0000006d101ffa88:  0000000000ef6da0  0000000002030000 
0000006d101ffa98:  0000000000de61d6  0000000000000004 
0000006d101ffaa8:  0000000000000240  000000000090d628 <runtime.stdcall+104> 
0000006d101ffab8:  0000021d58580000  0000000000000008 
0000006d101ffac8:  0000000000d1e603  0000000000000000 
0000006d101ffad8:  00000000011ca180  00000000012025c0 
0000006d101ffae8:  0000021d585849b8  000000c0000d7d18 
0000006d101ffaf8:  0000000002030000  0000000000000000 
0000006d101ffb08:  0000000000ea0de3  0000000000d30070 
0000006d101ffb18:  0000000000d14c30  0000000000d177e0 
0000006d101ffb28:  0000000000d2fcb0  0000000000000000 
0000006d101ffb38:  0000021d58581ce0  0000021d585849b8 
0000006d101ffb48:  000000c0000d7d18  0000006d101ffbf0 
runtime: unknown pc 0xde4165
stack: frame={sp:0x6d101ffa58, fp:0x0} stack=[0x0,0x6d101ffc70)
0000006d101ff958:  0000000000000061  0000000000000008 
0000006d101ff968:  0000000000de8a32  0000000000000001 
0000006d101ff978:  0000000000de5500  000000000000c000 
0000006d101ff988:  0000021d00000000  656d68732d636367 
0000006d101ff998:  6f2d326d64742d6d  626f6c675f65636e 
0000006d101ff9a8:  6d656d68735f6c61  616161616161612d 
0000006d101ff9b8:  6161616161616161  6161616161616161 
0000006d101ff9c8:  4141416161616141  6141416141614161 
0000006d101ff9d8:  6141416141616161  4141416161616161 
0000006d101ff9e8:  6161614161614161  0000000000000000 
0000006d101ff9f8:  0000000000000000  0000021d58580000 
0000006d101ffa08:  00000020c1aa73d4  0000021d58580000 
0000006d101ffa18:  0000000000ef6da0  0000000000debb40 
0000006d101ffa28:  000000c0000d7d18  0000000002030000 
0000006d101ffa38:  0000000000000000  0000000000000018 
0000006d101ffa48:  0000000000000007  0000006d101ffbf0 
0000006d101ffa58: <0000000000de438b  0000021d58580000 
0000006d101ffa68:  00007fffc1aa73d4  0000021d58580000 
0000006d101ffa78:  0000021d40000062  0000000000000001 
0000006d101ffa88:  0000000000ef6da0  0000000002030000 
0000006d101ffa98:  0000000000de61d6  0000000000000004 
0000006d101ffaa8:  0000000000000240  000000000090d628 <runtime.stdcall+104> 
0000006d101ffab8:  0000021d58580000  0000000000000008 
0000006d101ffac8:  0000000000d1e603  0000000000000000 
0000006d101ffad8:  00000000011ca180  00000000012025c0 
0000006d101ffae8:  0000021d585849b8  000000c0000d7d18 
0000006d101ffaf8:  0000000002030000  0000000000000000 
0000006d101ffb08:  0000000000ea0de3  0000000000d30070 
0000006d101ffb18:  0000000000d14c30  0000000000d177e0 
0000006d101ffb28:  0000000000d2fcb0  0000000000000000 
0000006d101ffb38:  0000021d58581ce0  0000021d585849b8 
0000006d101ffb48:  000000c0000d7d18  0000006d101ffbf0 

goroutine 1 [syscall]:
github.com/AllenDang/giu/imgui._Cfunc_iggIoSetIniFilename(0x21d585849b8, 0x21d58581ce0)
	_cgo_gotypes.go:3113 +0x4c
github.com/AllenDang/giu/imgui.IO.SetIniFilename.func1(0x21d585849b8, 0x21d58581ce0)
	C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/giu@v0.0.0-20201013041703-ec1448f8c506/imgui/IO.go:162 +0x77
github.com/AllenDang/giu/imgui.IO.SetIniFilename(0x21d585849b8, 0x0, 0x0)
	C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/giu@v0.0.0-20201013041703-ec1448f8c506/imgui/IO.go:162 +0xe6
github.com/AllenDang/giu.NewMasterWindow(0xf8ad49, 0xa, 0x258, 0x1f4, 0x1, 0x0, 0x0)
	C:/Users/Administrator/go/pkg/mod/github.com/!allen!dang/giu@v0.0.0-20201013041703-ec1448f8c506/MasterWindow.go:45 +0xf3
main.main()
	C:/Users/Administrator/go/src/ssjc/imguidemo/main.go:44 +0x5d
rax     0x0
rbx     0xef6da0
rcx     0x58581f3d
rdi     0xc0000d7d18
rsi     0xdebb40
rbp     0x6d101ffbf0
rsp     0x6d101ffa58
r8      0x6d101ff938
r9      0x6d101ffa60
r10     0x0
r11     0x246
r12     0x2030000
r13     0x0
r14     0x18
r15     0x7
rip     0xde4165
rflags  0x10246
cs      0x33
fs      0x53
gs      0x2b

**Comment by wiktorkujawa** [comment]
When I run this I also get exit status and I think that it's considered with opengl and glfw, because when I tried to build wasm file with tinygo: 
tinygo build -o main.wasm -target wasm ./main.go

I got this error:

```
$ tinygo build -o main.wasm -target wasm ./main.go
# github.com/go-gl/gl/v3.2-core/gl
..\github.com\go-gl\gl\v3.2-core\gl\package.go:19:9: not implemented: build constraints in #cgo line
..\github.com\go-gl\gl\v3.2-core\gl\package.go:20:9: not implemented: build constraints in #cgo line
..\github.com\go-gl\gl\v3.2-core\gl\package.go:21:9: not implemented: build constraints in #cgo line
..\github.com\go-gl\gl\v3.2-core\gl\package.go:22:9: not implemented: build constraints in #cgo line
..\github.com\go-gl\gl\v3.2-core\gl\procaddr.go:19:6: not implemented: build constraints in #cgo line
..\github.com\go-gl\gl\v3.2-core\gl\procaddr.go:20:6: not implemented: build constraints in #cgo line
..\github.com\go-gl\gl\v3.2-core\gl\procaddr.go:21:6: not implemented: build constraints in #cgo line
..\github.com\go-gl\gl\v3.2-core\gl\procaddr.go:22:6: not implemented: build constraints in #cgo line
..\github.com\go-gl\gl\v3.2-core\gl\procaddr.go:23:6: not implemented: build constraints in #cgo line
..\github.com\go-gl\gl\v3.2-core\gl\procaddr.go:24:6: not implemented: build constraints in #cgo line
..\github.com\go-gl\gl\v3.2-core\gl\procaddr.go:25:6: not implemented: build constraints in #cgo line
..\github.com\go-gl\gl\v3.2-core\gl\procaddr.go:26:6: not implemented: build constraints in #cgo line
..\github.com\go-gl\gl\v3.2-core\gl\package.go:108:26: unknown C type: void () (libclang type kind FunctionNoProto)
..\github.com\go-gl\gl\v3.2-core\gl\package.go:141:26: unknown C type: void () (libclang type kind FunctionNoProto)
..\github.com\go-gl\gl\v3.2-core\gl\package.go:142:26: unknown C type: void () (libclang type kind FunctionNoProto)
..\github.com\go-gl\gl\v3.2-core\gl\package.go:251:28: unknown C type: GLuint () (libclang type kind FunctionNoProto)
..\github.com\go-gl\gl\v3.2-core\gl\package.go:353:26: unknown C type: void () (libclang type kind FunctionNoProto)
..\github.com\go-gl\gl\v3.2-core\gl\package.go:354:26: unknown C type: void () (libclang type kind FunctionNoProto)
..\github.com\go-gl\gl\v3.2-core\gl\package.go:359:26: unknown C type: void () (libclang type kind FunctionNoProto)
..\github.com\go-gl\gl\v3.2-core\gl\package.go:360:26: unknown C type: void () (libclang type kind FunctionNoProto)
..\github.com\go-gl\gl\v3.2-core\gl\package.go:362:26: unknown C type: void () (libclang type kind FunctionNoProto)
..\github.com\go-gl\gl\v3.2-core\gl\package.go:363:26: unknown C type: void () (libclang type kind FunctionNoProto)
..\github.com\go-gl\gl\v3.2-core\gl\package.go:371:26: unknown C type: void () (libclang type kind FunctionNoProto)
..\github.com\go-gl\gl\v3.2-core\gl\package.go:437:28: unknown C type: GLenum () (libclang type kind FunctionNoProto)
..\github.com\go-gl\gl\v3.2-core\gl\package.go:448:28: unknown C type: GLenum () (libclang type kind FunctionNoProto)
..\github.com\go-gl\gl\v3.2-core\gl\package.go:449:28: unknown C type: GLenum () (libclang type kind FunctionNoProto)
..\github.com\go-gl\gl\v3.2-core\gl\package.go:450:28: unknown C type: GLenum () (libclang type kind FunctionNoProto)
..\github.com\go-gl\gl\v3.2-core\gl\package.go:839:26: unknown C type: void () (libclang type kind FunctionNoProto)
..\github.com\go-gl\gl\v3.2-core\gl\package.go:852:26: unknown C type: void () (libclang type kind FunctionNoProto)
..\github.com\go-gl\gl\v3.2-core\gl\package.go:853:26: unknown C type: void () (libclang type kind FunctionNoProto)
..\github.com\go-gl\gl\v3.2-core\gl\package.go:854:26: unknown C type: void () (libclang type kind FunctionNoProto)
..\github.com\go-gl\gl\v3.2-core\gl\package.go:1012:26: unknown C type: void () (libclang type kind FunctionNoProto)
..\github.com\go-gl\gl\v3.2-core\gl\package.go:1016:26: unknown C type: void () (libclang type kind FunctionNoProto)
..\github.com\go-gl\gl\v3.2-core\gl\package.go:1017:26: unknown C type: void () (libclang type kind FunctionNoProto)
..\github.com\go-gl\gl\v3.2-core\gl\package.go:1078:26: unknown C type: void () (libclang type kind FunctionNoProto)
..\github.com\go-gl\gl\v3.2-core\gl\package.go:1079:26: unknown C type: void () (libclang type kind FunctionNoProto)
```

And in problems I got this:
```
No packages found for open file C:\Users\myUserDirectory\go\src\github.com\go-gl\gl\v3.2-core\gl\package.go: <nil>.
If this file contains build tags, try adding "-tags=<build tag>" to your gopls "buildFlag" configuration (see (https://github.com/golang/tools/blob/master/gopls/doc/settings.md#buildflags-string).
Otherwise, see the troubleshooting guidelines for help investigating (https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md).
```

But I don't know what to do with this, because I just started with tinygo. If someone knew how to compile this, please answer.
